const flashcards = [
    {
        id: 1,
        name: "Tomato",
        image: "https://example.com/images/tomato.jpg",
        type: "Fruit",
        difficulty: "medium",
        facts: [
            "Botanically, tomatoes are classified as berries.",
            "They are rich in lycopene, an antioxidant.",
            "Often mistaken as a vegetable due to culinary use.",
        ],
        flip: true,
    },
    {
        id: 2,
        name: "Carrot",
        image: "https://example.com/images/carrot.jpg",
        type: "Vegetable",
        difficulty: "easy",
        facts: [
            "Carrots are root vegetables.",
            "They are high in beta-carotene, which converts to vitamin A.",
            "Originally cultivated for their leaves and seeds.",
        ],
        flip: true,
    },
    {
        id: 3,
        name: "Cucumber",
        image: "https://example.com/images/cucumber.jpg",
        type: "Fruit",
        difficulty: "medium",
        facts: [
            "Cucumbers develop from the flower of the plant.",
            "They have seeds inside, making them fruits botanically.",
            "Mostly used in savory dishes like a vegetable.",
        ],
        flip: true,
    },
    {
        id: 4,
        name: "Bell Pepper",
        image: "https://example.com/images/bellpepper.jpg",
        type: "Fruit",
        difficulty: "easy",
        facts: [
            "Bell peppers contain seeds and grow from flowers.",
            "They come in a variety of colors like red, green, and yellow.",
            "Often treated as vegetables in cooking.",
        ],
        flip: true,
    },
    {
        id: 5,
        name: "Broccoli",
        image: "https://example.com/images/broccoli.jpg",
        type: "Vegetable",
        difficulty: "hard",
        facts: [
            "Broccoli is a flowering vegetable.",
            "It belongs to the cabbage family.",
            "You eat the flower and stem portions of the plant.",
        ],
        flip: true,
    },
    {
        id: 6,
        name: "Avocado",
        image: "https://example.com/images/avocado.jpg",
        type: "Fruit",
        difficulty: "medium",
        facts: [
            "Avocados have a single large seed inside.",
            "They are rich in healthy fats.",
            "Botanically classified as a large berry.",
        ],
        flip: true,
    },
    {
        id: 7,
        name: "Potato",
        image: "https://example.com/images/potato.jpg",
        type: "Vegetable",
        difficulty: "easy",
        facts: [
            "Potatoes are underground tubers.",
            "They are a staple food in many cultures.",
            "High in carbohydrates and used in countless dishes.",
        ],
        flip: true,
    },
    {
        id: 8,
        name: "Pumpkin",
        image: "https://example.com/images/pumpkin.jpg",
        type: "Fruit",
        difficulty: "hard",
        facts: [
            "Pumpkins grow from flowers and contain seeds.",
            "They are a type of squash.",
            "Commonly associated with autumn and Halloween.",
        ],
        flip: true,
    },
    {
        id: 9,
        name: "Spinach",
        image: "https://example.com/images/spinach.jpg",
        type: "Vegetable",
        difficulty: "medium",
        facts: [
            "Spinach is a leafy green vegetable.",
            "Rich in iron and other nutrients.",
            "Was made popular by the cartoon character Popeye.",
        ],
        flip: true,
    },
    {
        id: 10,
        name: "Zucchini",
        image: "https://example.com/images/zucchini.jpg",
        type: "Fruit",
        difficulty: "hard",
        facts: [
            "Zucchini is botanically a fruit.",
            "It's a type of summer squash.",
            "Usually prepared and eaten like a vegetable.",
        ],
        flip: true,
    },
];

export default flashcards;
